version: '3.4'
services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - 4879:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - C:\log:/var/lib/mysql
    networks:
      - node-net

  back-end:
    image: gustavomoraesfonseca/node:latest
    container_name: node
    ports:
      - 8080:8080
    environment:
      MYSQL_IP: mysql
      MYSQL_PORT: 4879
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - node-net

networks:
  node-net:
    driver: bridge